---
development:
  DB_KEY: "ygNiffMFsPo/V9tEuGY25bijZNlf3AkUQqJrS/YG+QM="
  VERIFY_KEY: "7ql7Fiw3cLyIbpiIhpXBjjg1v2/raloy3mVEkNwesWY="
test:
  DB_KEY: "ygNiffMFsPo/V9tEuGY25bijZNlf3AkUQqJrS/YG+QM="
  VERIFY_KEY: "7ql7Fiw3cLyIbpiIhpXBjjg1v2/raloy3mVEkNwesWY="
